# Generated by Django 2.2.1 on 2019-06-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190627_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapp',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='female', max_length=6, verbose_name='性别'),
        ),
    ]
