# Generated by Django 2.2.1 on 2019-07-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20190619_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='index',
            field=models.IntegerField(default=0, verbose_name='轮播顺序'),
        ),
    ]
